# -*- coding: utf-8 -*-
"""helloworld.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15fze1KMHAyaWcccfE1pw9v-8irA67w_G
"""

#printing hello world in python
print("Hello World")